---
network_ports:
  - switches:
      - s1-leaf3
    switch_ports:
      - Ethernet6
    enabled: true
    mtu: 9000
    profile: int_routed_host
    structured_config:
      ip_address: 10.192.36.254/24
      vrf: bluevrf
      description: test eth6 routed port
      mtu:
